### ISSUE TITLE
Same Client window during same /string

### ISSUE THREAD

**Issue by romacron** [fabiang/xmpp#13]
Hello,
I combine this framework with an native chat client(psi)
While sending some messages from php console it opens everytime an new "window-inanstane"  in psi
During some comparisons the window based up the "client-string" -> "2158401630142528489031240"

<iq from='user2@my.de' to='user1@my.de/2158401630142528489031240' id='fabiang_xmpp_54f41f1d32749' type='result'><query xmlns='jabber:iq:roster'><item subscription='from' jid='user2@my.de'/></query></iq>' from 'tcp://my.de:5222

Is it possible to set this client string "user1@my.de/user1FromConsole" or other static vars?

So i will get the same window for the same session.

Thx !

**Comment by a-komarev** [comment]
I've wrote extension of this repository. Will make PR very soon. You can check it working this way at this moment:

**composer.json**
```json
"require": {
    "fabiang/xmpp": "dev-feature/set-jid-resource"
},
"repositories": [
    {
        "type": "git",
        "url": "https://github.com/cybercog/fabiang-xmpp"
    }
],
```

After that if you set username in options like `my-username@my-server.com/my-resource` - resource will be static.
