### ISSUE TITLE
How to connect to Google Talk

### ISSUE THREAD

**Issue by pstephan1187** [fabiang/xmpp#14]
I am trying to connect to Google Talk but am getting a `Stream Error: "host-unknown"` error. Any idea why? Here is my code:

```
$Options = new Options('tcp://talk.google.com:5222');
$Options->setUsername('username@gmail.com');
$Options->setPassword('*********');

$Client = new Client($Options);
$Client->connect();

$roster = $Client->send(new Roster);
$Client->disconnect();
```

Error occurs on `$Client->connect();`. I appreciate any help. Thanks!

**Comment by bensbox** [comment]
Google Talk has been discontinued -> https://xmpp.net/result.php?id=143034
You need to use a different server.

**Comment by pstephan1187** [comment]
Not sure how that service works, but I wrote my own script that connects to Google Talk's XMPP server just fine. The issue that I was running into when writing my own script was that you had to connect via TLS on port 5223 from the get-go. Connection via TCP over port 5222 and then establishing TLS was not working. That may be the issue here.

**Comment by fabiang** [comment]
Does that mean connecting to `tls://talk.google.com:5223/` works you?

**Comment by pstephan1187** [comment]
I didn't get that far using this library. It wasn't until hours of debugging in vanilla PHP before I figured that one out.

**Comment by ianfp** [comment]
This worked for me:

```php
$options = new Options('tcp://talk.google.com:5222');
$options->setUsername('username@gmail.com');
$options->setPassword('*********');
$options->setTo('gmail.com'); // This is the missing piece!

$client = new Client($options);
// ...
```
