### ISSUE TITLE
Help with receive message.

### ISSUE THREAD

**Issue by erickpessoa** [fabiang/xmpp#37]
Hi, Fabian...
Well I read issue #10 and I understands your answer. **I need register one function callback in EventManager to stay listening, when receive message, can it process.**
But I not got it how make this. You can help us with one example?

**I made tests but the registered event, not occur.**

since now thank you

**Comment by erickpessoa** [comment]
Hi, guys ... 
I was reading test cases, find a solution.

$client->getConnection()->receive();

**Comment by jorpeh** [comment]
Hi, Erick
Did you find any solution on how to receive incoming messages. Please if you could help me with an example, I'm stuck on that.
thanks
