### ISSUE TITLE
stream_socket_enable_crypto(): SSL operation failed with code 1 SSL routines:ssl3_get_server_certificate:certificate verify failed

### ISSUE THREAD

**Issue by vineet-287** [fabiang/xmpp#52]
I got this message when I upgrade my php >=5.6. This version has default `verify_peer` to `true`. Prior it was working fine. Either we should add ssl certificate in `apache` config or make falsy connection when trying to connect over ssl. How can I disable `verify_peer` while connecting.

**Comment by vineet-287** [comment]
I've modified the code and forked into my repo. Can anyone suggest how can I make changes in `fabiang/xmpp` repo ? Else please take a look @ [vineet-287/xmpp](https://github.com/vineet-287/xmpp)

**Comment by flaviu-chelaru** [comment]
No need for this.

You can just use the $options

```php

$options
                ->setUsername($user)
                ->setPassword($pass)
                ->setContextOptions(array(
                    'ssl' => array(
                        'verify_peer' => false,
                        'verify_peer_name' => false,
                        'allow_self_signed' => true,

                    )
                ));
```
Plus, your changes seem to be more than required ( you have styling changes )
