### ISSUE TITLE
composer require fabiang/xmpp (error)

### ISSUE THREAD

**Issue by rhemandaddy** [fabiang/xmpp#53]
Hello.
The following error is generated when I run composer require fabiang/xmpp

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package fabiang/xmpp No version set (parsed as 1.0.0) could not be found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

Could someone help me ??

**Comment by fabiang** [comment]
Did you try `composer require fabiang/xmpp=^0.7`?

**Comment by rhemandaddy** [comment]
I have the same error when I add the following code in my composer file.
"require": {
        "fabiang/xmpp": "^0.7"
    }
But When I replace "^0.7" by "*" everything seems to work.
"require": {
        "fabiang/xmpp": "*"
    }

**Comment by fabiang** [comment]
Something must be wrong with your environment. Are you using Toran Proxy or company internal Satis installation which maybe breaks the package?

When I run the following everything is ok:

> $ composer require fabiang/xmpp
> Using version ^0.7.0 for fabiang/xmpp
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Package operations: 2 installs, 0 updates, 0 removals
>   - Installing psr/log (1.0.2): Loading from cache
>   - Installing fabiang/xmpp (0.7.0): Downloading (100%)         
> fabiang/xmpp suggests installing psr/log-implementation (Allows more advanced logging of the xmpp > connection)
> Writing lock file
> Generating autoload files

**Comment by rhemandaddy** [comment]
Thanks a lot for your help. But I really dont know what's wrong. I checked my envorenment and now i have the following error.

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for fabiang/xmpp 1.0.x-dev -> satisfiable by fabiang/xmpp[1.0.x-dev].
    - Can only install one of: fabiang/xmpp[0.7.0, 1.0.x-dev].
    - Installation request for fabiang/xmpp ^0.7.0 -> satisfiable by fabiang/xmpp[0.7.0].

Installation failed, reverting ./composer.json to its original content.

**Comment by fabiang** [comment]
What's your minimum-stability flag in your `composer.json`?

Am 02.06.2017 13:21 schrieb "rhemandaddy" <notifications@github.com>:

**Comment by rhemandaddy** [comment]
I am using the following composer.json (the one you provide)
https://github.com/fabiang/xmpp/blob/master/composer.json

**Comment by fabiang** [comment]
You should create your own with composer init

Am 02.06.2017 13:32 schrieb "rhemandaddy" <notifications@github.com>:

I am using the following composer.json (the one you provide)
https://github.com/fabiang/xmpp/blob/master/composer.json

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/fabiang/xmpp/issues/53#issuecomment-305761736>, or mute
the thread

**Comment by rhemandaddy** [comment]
thanks a lot

**Comment by fabiang** [comment]
Btw you shouldn't use the `composer.json` provided by a project. The projects `composer.json` describes the projects dependencies and config. Of cause if your `composer.json` has the name project name in it like a package of a dependency you require, this lead of cause to naming conflicts and is terribly wrong ;)
