### ISSUE TITLE
Stream Error: \"host-""unknown\

### ISSUE THREAD

**Issue by abdelhafiddahhani** [fabiang/xmpp#71]
it doesn't work for me the connection

$options = new Options("tcp://192.168.110.20:5222");
$options->setUsername("admin@localhost")->setPassword("admin");
$client = new Client($options);
$client->connect();
error message :

message":"Stream Error: \"host-""unknown\"","class":"Fabiang\Xmpp\Exception\Stream\StreamErrorException","trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"C:\xampp\htdocs\API\vendor\fabiang\xmpp\src\Exception\Stream\StreamErrorException.php","line":77,"args":[]},""

Thank you

**Comment by youmad** [comment]
@abdelhafiddahhani same issue has been resolved in #38 (and also please check this #19).

**Comment by abdelhafiddahhani** [comment]
Thank you Mr. Youmad i fixed the probléme so now if i want to register a new user from PHP how i do this plz ! if you a=have eny experience with help me 

Thank you
