### ISSUE TITLE
stream_socket_client(): Failed to enable crypto

### ISSUE THREAD

**Issue by abdelhafiddahhani** [fabiang/xmpp#72]
my code 

$options = new Options("tcp://localhost:5280");
            $options->setUsername("admin@localhost")->setPassword("admin");
            $client = new Client($options);
            $client->connect();

Error i got : 
code":500,"message":"Internal Server Error","exception":[{"message":"stream_socket_client(): Failed to enable crypto","class":"Fabiang\\Xmpp\\Exception\\ErrorException","trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/API\/vendor\/fabiang\/xmpp\/src\/Stream\/SocketClient.php","line":118,"args":[]},{"namespace":"Fabiang\\Xmpp\\Util","short_class":"ErrorHandler","class":"Fabiang\\Xmpp\\Util\\ErrorHandler","type":"->","function":"Fabiang\\Xmpp\\Util\\{closure}","file":null,"line":null,"args":[["integer",2],["string","stream_socket_client(): Failed to enable crypto"],["string","\/var\/www\/html\/API\/vendor\/fabiang\/xmpp\/src\/Stream\/SocketClient.php"],["integer",111],["array",{"address":["string","tls:\/\/localhost:5280"],"timeout":["integer",30],"flags":["integer",4],"options":["array",[]],"errno":["integer",0],"errstr":["string",""]}]]},

anyone can help me plz 
Thank you

**Comment by youmad** [comment]
@abdelhafiddahhani please provide your XMPP server configuration.
