### ISSUE TITLE
Receive message

### ISSUE THREAD

**Issue by andriusvo** [fabiang/xmpp#84]
Hey guys,

I already seen a lot of topics about receiving messages but no one helped for me and I can't understand how to receive message.

For testing purposes I'm using 616.pub server to send messages to user.
F.e. I authenticated as User1 (using this library). Next step is I'm waiting for User2 (from 616.pub server) to send me a message. When User2 sent a message I want to receive it, but

`$input = $client->getConnection()->receive();` is not working.

May be I'm doing something wrong?

``
$client = new Client($options);
 $client->connect();
 $input = $client->getConnection()->receive();
``

**Comment by youmad** [comment]
@SSMellow, have you tried [this](https://github.com/fabiang/xmpp/issues/12#issuecomment-94091169)?

**Comment by andriusvo** [comment]
@youmad yeah, It works, but then I Iterate through DomDocument to get all DomElements, I only get one DOMElement which contains tagName `stream:stream` without any value (message)

**Comment by youmad** [comment]
Well, @SSMellow, I think you should implement your own event listener and catch events like message, body and subject. Maybe you will have to fork this repo and modify some parts to be able to raise these events. Anyway, you can try do debug events, raises during `\Fabiang\Xmpp\Stream\XMLStream::parse()`, I think it can help you.

**Comment by youmad** [comment]
> but then I Iterate through DomDocument to get all DomElements, I only get one DOMElement which contains tagName `stream:stream` without any value (message)

Try to dump the whole variable and look onto it instead.
